# Generated by Django 4.1.7 on 2023-04-24 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('AC', 'Action'), ('COM', 'Comedie'), ('DRA', 'Drame'), ('SF', 'Sciencefiction'), ('HOR', 'Horreur'), ('ROM', 'Romance'), ('THRI', 'Thriller'), ('ANIM', 'Animation')], max_length=5)),
                ('biography', models.CharField(max_length=1000)),
                ('year_formed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2023)])),
                ('active', models.BooleanField(default=True)),
                ('official_homepage', models.URLField(blank=True, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('sold', models.BooleanField(default=True)),
                ('year', models.IntegerField()),
                ('type', models.CharField(choices=[('RCRD', 'Records'), ('CLOTH', 'Clothing'), ('POST', 'Posters'), ('MIS', 'Miscellaneous')], max_length=10)),
            ],
        ),
    ]
